### ISSUE TITLE
Host API docs

### ISSUE THREAD

**Issue by akshgpt7** [metacall/core#125]
## Description
It would be really convenient to refer the MetaCall API, if its API docs are hosted somewhere. Currently, to reference the API, one has to look around in the header file declarations. Both for the [`metacall_value.h`](https://github.com/metacall/core/blob/develop/source/metacall/include/metacall/metacall_value.h) and [`metacall.h`](https://github.com/metacall/core/blob/develop/source/metacall/include/metacall/metacall.h).

We can build them locally, but it's pretty time-consuming and not ideal at all. It would be much easier to refer and search content if they're hosted at one place.

The header files already have all the documentation generating comments, so just using an automatic doc generator and hosting it should do.

**Comment by viferga** [comment]
Done: https://core.metacall.io/api/html/index.html

Here's the repo: https://github.com/metacall/landing-page
