### ISSUE TITLE
NodeJS Loader class is not implemented on ML example

### ISSUE THREAD

**Issue by JSMonk** [metacall/core#132]
## 🐛 Bug Report

I've tried to run [the example](https://github.com/metacall/ml-news-article-scraper-example) with core `0.4.3` version and got the error with stack trace.

### Expected Behavior
Run node.js without an error

### Current Behavior
Throw the error like `NodeJS Loader Error: NodeJS Loader class is not implemented`

### Possible Solution
Seems like it's related to the new API feature presented after HolyJS conference

### Steps to Reproduce

1. clone https://github.com/metacall/ml-news-article-scraper-example repo
2. install all of the python and nodejs dependencies
3. run `metacall app.js`

### Context (Environment)
macOS Docker

**Comment by viferga** [comment]
This has been mitigated but the proper solution would be to implement class support in NodeJS.

**Comment by viferga** [comment]
This should be solved once this PR is merged: https://github.com/metacall/core/pull/343
