### ISSUE TITLE
Errors in the Ruby Loader

### ISSUE THREAD

**Issue by HarshCasper** [metacall/core#163]
## 🐛 Bug Report

I created a file named `app.rb` and pushed the following code into the same: 

```
[hmishra@hmishra ~]$ cat app.rb
$i = 0
$num = 5

while $i < $num  do
   puts("Inside the loop i = #$i" )
   $i +=1
end
```
On trying to execute it through MetaCall CLI, I get the following output: 

```
[hmishra@hmishra ~]$ metacall app.rb
Inside the loop i = 0
Inside the loop i = 1
Inside the loop i = 2
Inside the loop i = 3
Inside the loop i = 4
Error: Ruby module evaluation failed
Error: Ruby module backtrace not available
Error: Invalid ruby module loading app.rb
Error: No module could be loaded
Script (app.rb) load error in loader (rb)
```

### Expected Behavior

It should not throw any errors.

### Current Behavior

It shows the errors in the Ruby Loader and displays that no module could be loaded and the evaluation has failed.

**Comment by viferga** [comment]
Solved: https://github.com/metacall/core/commit/7be3cb58f05d418d15fe23db783902b0b4e6d7af
