### ISSUE TITLE
Destory not exit bug

### ISSUE THREAD

**Issue by HolidayXue** [metacall/core#183]
## 🐛 Bug Report

emebing js into c++ code
when call the function that name is metacall_destroy
MetaCall Embedding NodeJS Example
static int cleanup(int code)
{
	if (metacall_destroy() != 0)
	{
		return code != 0 ? -code : -255;
	}

	return code;
}

block in node_loader_impl.cpp file
function name  ‘node_loader_impl_destroy’

console log out
MetaCall Library 0.1.0
Copyright (C) 2016 - 2021 Vicente Eduardo Ferrer Garcia <vic798@gmail.com>
Compiled as shared library type
Debug: Initializing MetaCall <00007FFF91D22558>
Debug: Global configuration loaded from configurations\global.json
Debug: Loading serial plugin: rapid_json_seriald
Debug: Loading serial symbol: rapid_json_serial_impl_interface_singleton
NodeJS Warning: MetaCall could not be preloaded
Function sum returned: 7.000000
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       20        -           19          -            0           +       0       +     0
Number of active handles: 22
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     0
Number of user active handles: 1
[-AI] async    00007FFF283CE4A0
[-A-] async    00000250EA0985A0
[-A-] async    00007FFF280C3170
[-A-] check    00000250EBC6C920
[-A-] prepare  00000250EBC6CA10
[-A-] check    00000250EBC6CA88
[-A-] async    00000250EBC6CB00
[-A-] async    00007FFF280C32D0
[RA-] async    00000250EBB60C00
[RA-] async    00000250EBCA5250
[RA-] async    00000250EBB3D8E0
[RA-] async    00000250EBBAC3D0
[RA-] async    00000250EBCBF340
[RA-] async    00000250EBB9ED80
[RA-] async    00000250EBBB3D90
[RA-] async    00000250EBBB3F80
[RA-] async    00000250EBBB4170
[RA-] async    00000250EBCB9370
[RA-] async    00000250EBCB9560
[RA-] async    00000250EBCB9750
[-A-] signal   00000250EBCAECB8
[RA-] prepare  00000250EA013058
[RA-] check    00000250EA0130D0
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     0
Number of active handles: 22
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     0
Number of user active handles: 1
[-AI] async    00007FFF283CE4A0
[-A-] async    00000250EA0985A0
[-A-] async    00007FFF280C3170
[-A-] check    00000250EBC6C920
[-A-] prepare  00000250EBC6CA10
[-A-] check    00000250EBC6CA88
[-A-] async    00000250EBC6CB00
[-A-] async    00007FFF280C32D0
[RA-] async    00000250EBB60C00
[RA-] async    00000250EBCA5250
[RA-] async    00000250EBB3D8E0
[RA-] async    00000250EBBAC3D0
[RA-] async    00000250EBCBF340
[RA-] async    00000250EBB9ED80
[RA-] async    00000250EBBB3D90
[RA-] async    00000250EBBB3F80
[RA-] async    00000250EBBB4170
[RA-] async    00000250EBCB9370
[RA-] async    00000250EBCB9560
[RA-] async    00000250EBCB9750
[-A-] signal   00000250EBCAECB8
[RA-] prepare  00000250EA013058
[RA-] check    00000250EA0130D0
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     0
Number of active handles: 22
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     0
Number of user active handles: 1
[-AI] async    00007FFF283CE4A0
[-A-] async    00000250EA0985A0
[-A-] async    00007FFF280C3170
[-A-] check    00000250EBC6C920
[-A-] prepare  00000250EBC6CA10
[-A-] check    00000250EBC6CA88
[-A-] async    00000250EBC6CB00
[-A-] async    00007FFF280C32D0
[RA-] async    00000250EBB60C00
[RA-] async    00000250EBCA5250
[RA-] async    00000250EBB3D8E0
[RA-] async    00000250EBBAC3D0
[RA-] async    00000250EBCBF340
[RA-] async    00000250EBB9ED80
[RA-] async    00000250EBBB3D90
[RA-] async    00000250EBBB3F80
[RA-] async    00000250EBBB4170
[RA-] async    00000250EBCB9370
[RA-] async    00000250EBCB9560
[RA-] async    00000250EBCB9750
[-A-] signal   00000250EBCAECB8
[RA-] prepare  00000250EA013058
[RA-] check    00000250EA0130D0
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     0
Number of active handles: 22
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     0
Number of user active handles: 1
[-AI] async    00007FFF283CE4A0
[-A-] async    00000250EA0985A0
[-A-] async    00007FFF280C3170
[-A-] check    00000250EBC6C920
[-A-] prepare  00000250EBC6CA10
[-A-] check    00000250EBC6CA88
[-A-] async    00000250EBC6CB00
[-A-] async    00007FFF280C32D0
[RA-] async    00000250EBB60C00
[RA-] async    00000250EBCA5250
[RA-] async    00000250EBB3D8E0
[RA-] async    00000250EBBAC3D0
[RA-] async    00000250EBCBF340
[RA-] async    00000250EBB9ED80
[RA-] async    00000250EBBB3D90
[RA-] async    00000250EBBB3F80
[RA-] async    00000250EBBB4170
[RA-] async    00000250EBCB9370
[RA-] async    00000250EBCB9560
[RA-] async    00000250EBCB9750
[-A-] signal   00000250EBCAECB8
[RA-] prepare  00000250EA013058
[RA-] check    00000250EA0130D0
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     0
Number of active handles: 22
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     0
Number of user active handles: 1
[-AI] async    00007FFF283CE4A0
[-A-] async    00000250EA0985A0
[-A-] async    00007FFF280C3170
[-A-] check    00000250EBC6C920
[-A-] prepare  00000250EBC6CA10
[-A-] check    00000250EBC6CA88
[-A-] async    00000250EBC6CB00
[-A-] async    00007FFF280C32D0
[RA-] async    00000250EBB60C00
[RA-] async    00000250EBCA5250
[RA-] async    00000250EBB3D8E0
[RA-] async    00000250EBBAC3D0
[RA-] async    00000250EBCBF340
[RA-] async    00000250EBB9ED80
[RA-] async    00000250EBBB3D90
[RA-] async    00000250EBBB3F80
[RA-] async    00000250EBBB4170
[RA-] async    00000250EBCB9370
[RA-] async    00000250EBCB9560
[RA-] async    00000250EBCB9750
[-A-] signal   00000250EBCAECB8
[RA-] prepare  00000250EA013058
[RA-] check    00000250EA0130D0
[-A-] timer    00000250EBB20B08
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     0
Number of active handles: 22
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     0
Number of user active handles: 1
[-AI] async    00007FFF283CE4A0
[-A-] async    00000250EA0985A0
[-A-] async    00007FFF280C3170
[-A-] check    00000250EBC6C920
[-A-] prepare  00000250EBC6CA10
[-A-] check    00000250EBC6CA88
[-A-] async    00000250EBC6CB00
[-A-] async    00007FFF280C32D0
[RA-] async    00000250EBB60C00
[RA-] async    00000250EBCA5250
[RA-] async    00000250EBB3D8E0
[RA-] async    00000250EBBAC3D0
[RA-] async    00000250EBCBF340
[RA-] async    00000250EBB9ED80
[RA-] async    00000250EBBB3D90
[RA-] async    00000250EBBB3F80
[RA-] async    00000250EBBB4170
[RA-] async    00000250EBCB9370
[RA-] async    00000250EBCB9560
[RA-] async    00000250EBCB9750
[-A-] signal   00000250EBCAECB8
[RA-] prepare  00000250EA013058
[RA-] check    00000250EA0130D0
[-A-] timer    00000250EBB20B08
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     0
Number of active handles: 22
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     0
Number of user active handles: 1
[-AI] async    00007FFF283CE4A0
[-A-] async    00000250EA0985A0
[-A-] async    00007FFF280C3170
[-A-] check    00000250EBC6C920
[-A-] prepare  00000250EBC6CA10
[-A-] check    00000250EBC6CA88
[-A-] async    00000250EBC6CB00
[-A-] async    00007FFF280C32D0
[RA-] async    00000250EBB60C00
[RA-] async    00000250EBCA5250
[RA-] async    00000250EBB3D8E0
[RA-] async    00000250EBBAC3D0
[RA-] async    00000250EBCBF340
[RA-] async    00000250EBB9ED80
[RA-] async    00000250EBBB3D90
[RA-] async    00000250EBBB3F80
[RA-] async    00000250EBBB4170
[RA-] async    00000250EBCB9370
[RA-] async    00000250EBCB9560
[RA-] async    00000250EBCB9750
[-A-] signal   00000250EBCAECB8
[RA-] prepare  00000250EA013058
[RA-] check    00000250EA0130D0
[-A-] timer    00000250EBB20B08
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     0
Number of active handles: 22
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     0
Number of user active handles: 1
[-AI] async    00007FFF283CE4A0
[-A-] async    00000250EA0985A0
[-A-] async    00007FFF280C3170
[-A-] check    00000250EBC6C920
[-A-] prepare  00000250EBC6CA10
[-A-] check    00000250EBC6CA88
[-A-] async    00000250EBC6CB00
[-A-] async    00007FFF280C32D0
[RA-] async    00000250EBB60C00
[RA-] async    00000250EBCA5250
[RA-] async    00000250EBB3D8E0
[RA-] async    00000250EBBAC3D0
[RA-] async    00000250EBCBF340
[RA-] async    00000250EBB9ED80
[RA-] async    00000250EBBB3D90
[RA-] async    00000250EBBB3F80
[RA-] async    00000250EBBB4170
[RA-] async    00000250EBCB9370
[RA-] async    00000250EBCB9560
[RA-] async    00000250EBCB9750
[-A-] signal   00000250EBCAECB8
[RA-] prepare  00000250EA013058
[RA-] check    00000250EA0130D0
[-A-] timer    00000250EBB20B08
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     0
Number of active handles: 22
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     1
Number of user active handles: 2
[-AI] async    00007FFF283CE4A0
[-A-] async    00000250EA0985A0
[-A-] async    00007FFF280C3170
[-A-] check    00000250EBC6C920
[-A-] prepare  00000250EBC6CA10
[-A-] check    00000250EBC6CA88
[-A-] async    00000250EBC6CB00
[-A-] async    00007FFF280C32D0
[RA-] async    00000250EBB60C00
[RA-] async    00000250EBCA5250
[RA-] async    00000250EBB3D8E0
[RA-] async    00000250EBBAC3D0
[RA-] async    00000250EBCBF340
[RA-] async    00000250EBB9ED80
[RA-] async    00000250EBBB3D90
[RA-] async    00000250EBBB3F80
[RA-] async    00000250EBBB4170
[RA-] async    00000250EBCB9370
[RA-] async    00000250EBCB9560
[RA-] async    00000250EBCB9750
[-A-] signal   00000250EBCAECB8
[RA-] prepare  00000250EA013058
[RA-] check    00000250EA0130D0
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     1
Number of active handles: 22
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     1
Number of user active handles: 2
[-AI] async    00007FFF283CE4A0
[-A-] async    00000250EA0985A0
[-A-] async    00007FFF280C3170
[-A-] check    00000250EBC6C920
[-A-] prepare  00000250EBC6CA10
[-A-] check    00000250EBC6CA88
[-A-] async    00000250EBC6CB00
[-A-] async    00007FFF280C32D0
[RA-] async    00000250EBB60C00
[RA-] async    00000250EBCA5250
[RA-] async    00000250EBB3D8E0
[RA-] async    00000250EBBAC3D0
[RA-] async    00000250EBCBF340
[RA-] async    00000250EBB9ED80
[RA-] async    00000250EBBB3D90
[RA-] async    00000250EBBB3F80
[RA-] async    00000250EBBB4170
[RA-] async    00000250EBCB9370
[RA-] async    00000250EBCB9560
[RA-] async    00000250EBCB9750
[-A-] signal   00000250EBCAECB8
[RA-] prepare  00000250EA013058
[RA-] check    00000250EA0130D0
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     1
Number of active handles: 22
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     0
Number of user active handles: 1
[-AI] async    00007FFF283CE4A0
[-A-] async    00000250EA0985A0
[-A-] async    00007FFF280C3170
[-A-] check    00000250EBC6C920
[-A-] prepare  00000250EBC6CA10
[-A-] check    00000250EBC6CA88
[-A-] async    00000250EBC6CB00
[-A-] async    00007FFF280C32D0
[RA-] async    00000250EBB60C00
[RA-] async    00000250EBCA5250
[RA-] async    00000250EBB3D8E0
[RA-] async    00000250EBBAC3D0
[RA-] async    00000250EBCBF340
[RA-] async    00000250EBB9ED80
[RA-] async    00000250EBBB3D90
[RA-] async    00000250EBBB3F80
[RA-] async    00000250EBBB4170
[RA-] async    00000250EBCB9370
[RA-] async    00000250EBCB9560
[RA-] async    00000250EBCB9750
[-A-] signal   00000250EBCAECB8
[RA-] prepare  00000250EA013058
[RA-] check    00000250EA0130D0
[-A-] timer    00000250EBB20508
[active_handles] - [base_active_handles] - [extra_active_handles] + [active_reqs] + [closing]
       22        -           19          -            2           +       0       +     0
### Steps to Reproduce

1.
2.
3.
4.

**Comment by viferga** [comment]
@HolidayXue thanks for reporting, and sorry for lasting into answering. This is a bug that I have been trying to hunt. We are really near to tag the version v0.5 and it is going to be shipped with NodeJS +12, which solves the bug on the current implementation.

I am going to merge everything as soon as possible. How can I ping you once I have solved this in order to try it again?

**Comment by viferga** [comment]
By the way, did you try this on the last develop branch?

**Comment by viferga** [comment]
I am closing this, try the latest version (v0.5.3) and if you have more problems, please join our chats:
<div id="badges" align="center">
  <a href="https://t.me/joinchat/BMSVbBatp0Vi4s5l4VgUgg" alt="Discord">
    <img src="https://img.shields.io/static/v1?label=metacall&message=join&color=blue&logo=telegram&style=flat" /></a>

  <a href="https://discord.gg/upwP4mwJWa" alt="Discord">
    <img src="https://img.shields.io/discord/781987805974757426?label=discord&style=flat" /></a>

  <a href="https://matrix.to/#/#metacall:matrix.org" alt="Matrix">
    <img src="https://img.shields.io/matrix/metacall:matrix.org?label=matrix&style=flat" /></a>

  <a href="https://twitter.com/metacallio" alt="Twitter">
    <img src="https://img.shields.io/twitter/follow/metacallio?label=MetaCall" /></a>

  <a href="https://medium.com/@metacall/call-functions-methods-or-procedures-between-programming-languages-with-metacall-58cfece35d7" target="_blank"><img src="https://raw.githubusercontent.com/metacall/core/develop/deploy/images/overview.png" alt="M E T A C A L L" style="max-width:100%; margin: 0 auto;" width="350" height="auto"></a>
</div>
