### ISSUE TITLE
support Nim please

### ISSUE THREAD

**Issue by kobi2187** [metacall/core#217]
## 🚀 Feature
Can you add support for the Nim language?

**Comment by viferga** [comment]
@kobi2187 can Nim compile to C? We just added support for C, maybe you can use that for supporting Nim.

In any case, we are implementing now Rust too, if you have time, maybe you can start implementing Nim.

What's your use case by the way? It would be interesting to know what programming language are you going to mix with Nim.

**Comment by kobi2187** [comment]
yes, correct. right now I use a library called nimpy and build a .so binary in Nim, which can be exported to python (the python side simply imports the fast functions) then I can work with python gui frameworks like kivy.
But the other way around, a sort of binding is a very enticing prospect as well. If the language is fast enough, I can use its libraries, though vm languages need the whole runtime to be present (so a good solution locally, but not the best solution when deploying).
Anyway there are many possibilities and a high productivity potential for what you're doing with such interoperability.

**Comment by viferga** [comment]
> yes, correct.
> EDIT: to clarify: I am most interested in dotnet languages (say C# but afaik F# and others can all be "compiled back" to C# code with tools ILSpy etc.) and fast high level languages like rust.
> if your software is a transpiler, then high level languages like ruby, python, typescript. (transpiler because of their performance issues)

MetaCall is not a transpiler, it usually embeds other JITs or Runtimes in order to execute the other languages. You can use C#, it uses DotNet Core CLR in order to execute the C# code.

> Right now I use a library called nimpy and build a .so binary in Nim, which can be exported to python (the python side simply imports the fast functions) then I can work with python gui frameworks like kivy.

So basically you are saying that you are using Nim libraries compiled into .so from Python, is that right? This is the opposite to what I was saying before.

I recommend you to check this: https://github.com/metacall/core/blob/develop/docs/README.md#2-language-support

Let's say we implement the Nim Port: This will wrap the MetaCall C API and you will be able to use C, C#, TypeScript, NodeJS, Ruby, Python... from Nim, for example, using `numpy` Python module from Nim.

If we implement the Nim Loader: We will be able to import Nim packages into other languages, so for example, we will be able to use some Nim library from Python (similar to a C/C++ extension), but with all the boilerplate reduced.

Knowing this, can you clarify what are you interested in? Port or Loader?

> The other way around, like bindings or a compatibility layer to other languages is a very enticing prospect as well. If the language is fast enough, I can use its libraries, though vm languages need the whole runtime to be present (so a good solution locally, but not the best solution when deploying).

Related to the deployment, MetaCall is offered as binary self contained distribution, as Docker image and as Guix package, so it should be easy to deploy it.

**Comment by kobi2187** [comment]
For my purposes: mostly the Nim Port.
Others in the Nim community have started working on the other part.
see: https://forum.nim-lang.org/t/8479
Of course your solution is most likely more mature.

**Comment by kobi2187** [comment]
I started a Nim forum thread:
https://forum.nim-lang.org/t/8635

**Comment by viferga** [comment]
@kobi2187 if you have an example of a Nim wrapper around a C library I can write the port for Nim.

**Comment by viferga** [comment]
> I started a Nim forum thread: https://forum.nim-lang.org/t/8635

Respect to this, I am not sure how easy is going to be to insert GraalVM into Nim, and now we support almost the same or even more languages than them. Soon we will support Rust too.

**Comment by kobi2187** [comment]
Cool, many thanks for your efforts!

Here are a few example bindings:
https://nimble.directory/search?query=Bindings
https://nimble.directory/search?query=binding

maybe choose a small lib to see how it's done, and bigger ones if metacall requires special features.

There are a few tools:
1) https://github.com/nimterop/nimterop
2) https://github.com/PMunch/futhark
3) the built in tool: c2nim

I have little c/c++ experience, I used mainly high level languages
I think nimterop is the better choice (uses treesitter parser), 
though a new tool, futhark looks really promising. (uses clang parsing, so no issues with preprocessing macros etc)
c2nim attempts to understand c/c++, and sometimes provide a direct translation but if u get stuck with that approach, I'd try the other tools.

**Comment by viferga** [comment]
@kobi2187 I wrote a base project which is already working: https://github.com/metacall/core/commit/f449792d0e09f4536b50d964102812163036a0ba

For making it work you have either to compile metacall manually or pass the CFLAGS and LDFLAGS pointing to the binaries (if you installed it by using binaries).

The test is passing, in my opinion, the API should be wrapped through templates and simplify the invocation boilerplate. Do you want to keep working on it?

**Comment by viferga** [comment]
@kobi2187 I wanted to answer this in the Nim forum:
```
I wrote a small wrapper about the MetaCall C API: https://github.com/metacall/core/commit/f449792d0e09f4536b50d964102812163036a0ba

The test is invoking a NodeJS function from Nim. Here's the GitHub issue if you want to follow the thread: https://github.com/metacall/core/issues/217
```

But I am not receiving the confirmation email. My user there is **viferga**.

**Comment by kobi2187** [comment]
awesome work! amazing cooperation, thank you!  I need to learn MetaCall in order to figure out some enticing use cases, and promote to the community.
My Nim knowledge wrt macros and templates is quite low, but enthusiasts exist and it's not a hard job overall to make a nice api. I am sorry, currently my personal priorities are kind of set. I will see what can be done, after I get it to work.
I think it is very useful, there are already users trying to combine environments such as dotnet.

wrt the forum, i will ask, but please first try again, or with a new user. could be a temporary issue or just a man in charge that wasn't yet available at the time.

**Comment by viferga** [comment]
> awesome work! amazing cooperation, thank you! I need to learn MetaCall in order to figure out some enticing use cases, and promote to the community. My Nim knowledge wrt macros and templates is quite low, but enthusiasts exist and it's not a hard job overall to make a nice api. I am sorry, currently my personal priorities are kind of set. I will see what can be done, after I get it to work. I think it is very useful, there are already users trying to combine environments such as dotnet.
> 
> wrt the forum, i will ask, but please first try again, or with a new user. could be a temporary issue or just a man in charge that wasn't yet available at the time.

Can you post it on the Nim forum thread? So people from the community can contribute if they want to.

Can I close the issue?
