### ISSUE TITLE
Eval in Metacall CLI fails to parse spaces properly

### ISSUE THREAD

**Issue by AkechiShiro** [metacall/core#246]
### Expected Behavior
Code with spaces should be evaluated correctly inside the Metacall CLI.

### Current Behavior
At the moment, any code containing spaces raises an error when writing directly on the command line.
```
Welcome to Tijuana, tequila, sexo & marijuana.
λ eval py print("Home World")
Error: Python Error: [Type: <class 'SyntaxError'>]: ('unterminated string literal (detected at line 1)', ('0x55ee4773ea10-0x7ffd4eb3a6c0-11-1846774869', 1, 7, 'print("Home', 1, 7))
Traceback not available
Error: Python Error: [Type: <class 'SyntaxError'>]: ('unterminated string literal (detected at line 1)', ('0x55ee4773ea10-0x7ffd4eb3a6c0-11-1846774869', 1, 7, 'print("Home', 1, 7))
Traceback not available
Script 'print("Home' eval error in loader (py)
```

### Possible Solution

Either rework the parsing of arguments or put this as a goal along in the refactoring of the Metacall CLI for GSoC 2022.

### Steps to Reproduce

1. Inside a terminal, type `metacall` or `metacallcli`.
2. Input `eval py print("Hello World")`
3. See the error.

### Context (Environment)

People could wish to evaluate some code, they're writing inside the CLI and not inside any files whatsoever.

**Comment by kuraakhilesh8230** [comment]
"Hi, I am  kura akhilesh, a contributor to OpenForce 2022. I would like to work on this issue, could you please tell me how this issue works. I would be making a PR as soon as I am done with resolving the issue. Thank you"

**Comment by viferga** [comment]
Solved with this: https://github.com/metacall/core/pull/482
