### ISSUE TITLE
`metacall::inline` not available with the `metacall` crate

### ISSUE THREAD

**Issue by PIG208** [metacall/core#256]
### Current Behavior

```
  |
2 | use metacall::inline::py;
  |               ^^^^^^ could not find `inline` in `metacall`
```

### Possible Solution

Publish the sub crates to crates.io and use the published version as a fallback.

### Context (Environment)

When using the rust port, I would like to take advantage of the new inline support.

### Detailed Description

Since `inline` is added as one of the dependencies using a path, it is not available when the `metacall` crate gets published on `crates.io`, making the sub crate unusable unless installing from other sources like `git`.

**Comment by viferga** [comment]
Sorry I have closed this without notifying you @PIG208 . Can you check it out now if it works? The latest version is `0.3.0`: https://crates.io/crates/metacall

**Comment by PIG208** [comment]
Yes, it works now.
