### ISSUE TITLE
metcall/metall.h: No such file or directory

### ISSUE THREAD

**Issue by patdaburu** [metacall/core#282]
### Detailed Description

Hello.  I'm trying out metacall for the first time (_very excited_) with go on Ubuntu 20.04.  When I call `metacall.Initialize()` I get an error about a missing header file (`metacall/metacall.h`).

I'm not sure that this is a "bug" since it's possible that I've botched the install, but I think I've followed the steps outlined and after looking around the Internet I haven't seen mention of this as a common problem.

Many, many thanks in advance for any advice!

### Steps to Reproduce
I used the installation instructions and ran:

`curl -sL https://raw.githubusercontent.com/metacall/install/master/install.sh | sh`

That seemed to work. 👍 

In my go app, I then imported `metacall` like so:

```
import (

	metacall "github.com/metacall/core/source/ports/go_port/source"
)
```

I then ran `go mod tidy`.

Then I added the following call:

```
	if err := metacall.Initialize(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
```

This is failing with the following error:

```
# github.com/metacall/core/source/ports/go_port/source
../../../go/pkg/mod/github.com/metacall/core/source/ports/go_port/source@v0.0.0-20220530142231-071efdc7374f/go_port.go:27:10: fatal error: metacall/metacall.h: No such file or directory
   27 | #include <metacall/metacall.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

### Context (Environment)
I'm running on Ubuntu 20.04 with go1.18.3 linux/amd64

When I search for `metacall.h` I do find it in this location:

`~/go/pkg/mod/github.com/metacall/core@v0.5.20/source/metacall/include/metacall/metacall.h`

Please let me know if I can provide more information that would be helpful.

**Comment by giarve** [comment]
@patdaburu  please check out this in the documentation 

https://github.com/metacall/core/tree/develop/source/ports/go_port/source#building

This section:
https://github.com/metacall/core/blob/071efdc7374f82678a2dcbdb5c8ca4d3481ce190/source/ports/go_port/source/README.md?plain=1#L62-L72

**Comment by patdaburu** [comment]
_D'oh!_  _Face palm!_ I completely missed this!  Thank you @giarve!!
