### ISSUE TITLE
Multiple errors while running tests

### ISSUE THREAD

**Issue by paramsiddharth** [metacall/core#285]
## 🐛 Bug Report

1. CTest truncates the output (it didn't for me, for @viferga's PC it did, needs investigation).
2. Several tests fail, false positives to be taken into account that need to be skipped.
3. The script continues despite errors which are only detected at the end (using Bash might be the solution).

### Steps to Reproduce
```bash
./docker-compose.sh test &> output
```

Log 1: https://gist.github.com/paramsiddharth/48e2ded5b828ceafd883c1ceb71f625d#file-output-txt
Log 2: https://gist.github.com/paramsiddharth/48e2ded5b828ceafd883c1ceb71f625d#file-output2-txt

**Comment by viferga** [comment]
This has to be properly addressed, most of them are false positives! I am going to solve the ones related to log. Please try to work on the CI/CD solution for solving it.

**Comment by viferga** [comment]
After avoiding the bug from logs, this is the list of errors:
```
          4 - rb_port (Failed)
         33 - metacall-test (Failed)
         56 - metacall-node-signal-handler-test (Failed)
         61 - metacall-inspect-test (Failed)
         62 - metacall-integration-test (Failed)
         64 - metacall-configuration-exec-path-test (Failed)
         85 - metacall-python-await-test (Failed)
         87 - metacall-python-node-await-test (Failed)
        119 - metacall-java-test (Failed)
        121 - metacall-wasm-python-port-test (Failed)
        127 - metacall-load-extension-test (Failed)
        129 - metacall-py-c-api-bench (Failed)
        133 - metacall-rb-call-bench (SEGFAULT)
```
Here's the full logs:
[output_sanitizer.txt](https://github.com/metacall/core/files/9003665/output_sanitizer.txt)

This is with log errors (your report):
```
	  4 - rb_port (Failed)
	 33 - metacall-test (Failed)
	 60 - metacall-inspect-test (Failed)
	 61 - metacall-integration-test (Failed)
	 63 - metacall-configuration-exec-path-test (Failed)
	 68 - metacall-python-open-test (Failed)
	 84 - metacall-python-await-test (Failed)
	 86 - metacall-python-node-await-test (Failed)
	109 - metacall-typescript-call-map-test (Failed)
	112 - metacall-typescript-require-test (Failed)
	115 - metacall-csharp-static-class-test (Failed)
	118 - metacall-java-test (Failed)
	120 - metacall-wasm-python-port-test (Failed)
	126 - metacall-py-c-api-bench (Failed)
	130 - metacall-rb-call-bench (SEGFAULT)
	150 - metacallcli-py-tsx (Failed)
```
