### ISSUE TITLE
signal handlers are not working when using node loader

### ISSUE THREAD

**Issue by amagdy19** [metacall/core#286]
## 🐛 Bug Report

I am using metacall shared library to embed nodejs code into my c++ application
inside my nodejs code I am spawning a child process
and I am connecting signal handlers inside c++
when the child process which is invoked from nodejs is finished SIGCHLD handler is not called in C++

### Steps to Reproduce
Using the attached [child_process_sample.zip](https://github.com/metacall/core/files/8968501/child_process_sample.zip)
The sample has three cases
1. run nodejs executable with JS file that spawn "ps" process
2. run metacall python loader and run py code that spawn "ps" process
3. run metacall node loader and run JS code that spawn "ps" process

**the C++ SIGCHLD handler will be called for cases 1 & 2 and will not be called for case#3**

To reproduce:
1. Prepare build environment
`setenv GCC_PATH <path to gcc directory that contains bin & lib directories>`
`setenv NODE_EXE <path to node executable>`
`setenv METACALL_BUILD <path to metacall build that contains lib directory>`
> The used metacall build has node loader and py loader
2. `cd child_process_sample`
3. `make`
4. `./invoke_app.sh`
5. the three cases will be run sequentially, you can notice that the log message "**c++: received signal SIGCHLD**" will be printed for cases 1 & 2 and will not be printed for case#3

### Context (Environment)
OS: CentOS Linux 7
Metacall: 0.2.22
gcc: 5.4.0
nodejs: 10.19.0

**Comment by amagdy19** [comment]
I have tried a workaround to catch SIGCHLD signal in nodejs then call a CPP callback function then inside the cpp callback function I call "raise(SIGCHLD)"
I found that the signal handler will not be called also
kindly find the attached [workaround.zip](https://github.com/metacall/core/files/8969046/workaround.zip)
try the same above steps to reproduce
the workaround source code is located in workaround.cpp

**Comment by viferga** [comment]
What about this? Does it fits your needs?

https://github.com/metacall/core/commit/8521b054e1d3ecf42064e9a11fccdd31c06899ac

**Comment by viferga** [comment]
I just realized, it does not propagate to the main thread. But this is basically due to the problem I told you, it runs in a different thread. I am going to do a workaround and share it as soon as possible.
