### ISSUE TITLE
Review design of CLI plugins

### ISSUE THREAD

**Issue by viferga** [metacall/core#302]
Respect to the PR: https://github.com/metacall/core/pull/298
We should take some considerations:

1) Should we use a different name for core_plugin? Like cli_plugin or cli_core_plugin?
2) We should load only the cli/core_plugin when we run metacallcli
3) Should we extend the execution path mechanism into plugin_extension? so instead of using an environment variable for locating the plugins, we can use our existing methodology for locating plugins? This will easily solve the point 2.

**Comment by rxbryan** [comment]
I have chosen to just add support for sub folders in plugin_extension https://github.com/metacall/core/pull/306
