### ISSUE TITLE
Metacallcli fails to load on MacOS Error: DynLink error: dlopen(/usr/local/Cellar/metacall/0.5.25/libplugin_extension.so, 9): image not found

### ISSUE THREAD

**Issue by AkechiShiro** [metacall/core#313]
## 🐛 Bug Report

The error when launching the latest built from source metacallcli.
```bash
/usr/local/Cellar/metacall/0.5.25/metacallcli
Error: DynLink error: dlopen(/usr/local/Cellar/metacall/0.5.25/libplugin_extension.so, 9): image not found
libc++abi: terminating with uncaught exception of type std::__1::__fs::filesystem::filesystem_error: filesystem error: in recursive_directory_iterator: No such file or directory [/usr/local/Cellar/metacall/0.5.25/lib/plugins/cli]
[1]    14309 abort      /usr/local/Cellar/metacall/0.5.25/metacallcli
```

### Expected Behavior

Should just work

### Current Behavior

During build : 
- `Installing: /usr/local/Cellar/metacall/0.5.25/lib/libplugin_extension.so`

- ls output inside the installation folder of metacall:
![image](https://user-images.githubusercontent.com/14914796/184030163-7a9c7d2c-fbc4-4b3e-b09b-7c640b1250ad.png)

### Context (Environment)

Under MacOS KVM BigSur using brew metacall.rb script to build metacall.

**Comment by viferga** [comment]
https://github.com/metacall/core/commit/aff4c635a0590ae31fdf08af48714a8c7d55242f
