### ISSUE TITLE
Tests fail for NodeJS on Windows

### ISSUE THREAD

**Issue by paramsiddharth** [metacall/core#333]
# 🐛 Bug Report
## Tests fail for NodeJS on Windows

Tests fail in the Windows CI for core due to being unable to locate `libnode.dll` correctly.
@viferga suggests this needs to be fixed via changes to the CMake configuration and has previously encountered and solved similar bugs.

![image](https://user-images.githubusercontent.com/30315706/187954850-714b33a4-a6fc-422f-b005-0017b62cb112.png)
[Logs](https://github.com/metacall/core/files/9471282/message.txt)

### Steps to Reproduce

1. Go to: https://github.com/paramsiddharth/metacall-core-detached/tree/tests/windows
2. Run the scripts inside a Windows container.
3. Notice how the tests fail.

**Comment by viferga** [comment]
We have to add a step in cmake for copying libnode.dll into the build folder and also install it later on contiguously to node_loader.dll. This is solved in windows distributable by manually copying it. And I used to do this manually too when developing in visual studio c++, but it should be done in an automated way so it's not a focus of errors for new developers.

**Comment by viferga** [comment]
I was checking the code and this is already handled when it is built from source, but as we are overriding everything in FindNodeJS.cmake, the best bet is what you proposed originally, copying the dll manually into the build folder:
https://github.com/metacall/distributable-windows/blob/acbb07452743add940cbc9026a4b3b1d2ae963bc/build.bat#L189

The build folder usually is:
./build/Debug
or
./build/Release
