### ISSUE TITLE
can not fetch correct array data returned by calling python function in golang

### ISSUE THREAD

**Issue by tangjiang** [metacall/core#353]
## 🐛 Bug Report

can not fetch correct array data returned by calling python function in golang

### Expected Behavior

fetch correct array data returned by calling python function in golang

### Detailed Description

python function:
```
def getArray():
    return list([5.0,4.0])
```
I have added some codes to [go_port.go](https://github.com/metacall/core/blob/develop/source/ports/go_port/source/go_port.go) file in the  valueToGo  function as below：
```
func valueToGo(value unsafe.Pointer) interface{} {

	v := C.metacall_value_id(value)
	switch v {
	case C.METACALL_INT:
		{
			return int(C.metacall_value_to_int(value))
		}

	case C.METACALL_FLOAT:
		{
			return float32(C.metacall_value_to_float(value))
		}

	case C.METACALL_DOUBLE:
		{
			return float64(C.metacall_value_to_double(value))
		}

	case C.METACALL_STRING:
		{
			return C.GoString(C.metacall_value_to_string(value))
		}
	case C.METACALL_ARRAY:
		{
			ptr := C.metacall_value_to_array(value)
			sz := (int)(C.metacall_value_size(value))
			count := (int)(C.metacall_value_count(value))

			interval := sz / count

			t := C.metacall_value_id(*ptr)
			p := uintptr(*ptr)
			switch t {

			case C.METACALL_DOUBLE:
				{
					r := make([]float64, count, count)

					for i := 0; i < count; i++ {
						j := *(*float64)(unsafe.Pointer(p + uintptr(i)*uintptr(interval)))
						r[i] = j
					}

					return r
				}
                       }
		}

		// TODO: Add more types
	}
	return nil
}
```

when i run this code as below:
```
ret, err := metacall.Call("getArray")

	if err != nil {
		t.Fatalf("%v", err)
	}
```

but can not get complete correct value of array returned by the python function, the code position as below:
```
j := *(*float64)(unsafe.Pointer(p + uintptr(i)*uintptr(interval)))
```

**Comment by viferga** [comment]
@tangjiang sorry for late answer, here's the code:
https://github.com/metacall/core/commit/f0515af5b8de398845a3c5999fa8ea5542ab7d47

Test it if it's all correct I will close the issue, you have a test to check how to use it.

**Comment by tangjiang** [comment]
It's all correct, thanks

**Comment by viferga** [comment]
@tangjiang cool, if you want more types implemented feel free to PR with it or create a new issue.
