### ISSUE TITLE
WASM build/tests fails in CI Windows

### ISSUE THREAD

**Issue by pkspyder007** [metacall/core#366]
## 🐛 Bug Report
When adding wasm to windows test ci action it fails to pass all tests.

### Expected Behavior
CI should pass all tests

### Current Behavior
Tests fail with error here's a log of CI action [WASM Logs](https://github.com/pkspyder007/metacall-core/actions/runs/3900700824/jobs/6661667680)

### Possible Solution
- The `wasm-loader` fails to load the `wasmloaderd.dll` since its missing the `wasttime.dll` dependency which is not being copied to the  `build/${BUILD_TYPE}` directory
There are 2 ways to fix this
1-  Update the build script  to copy the dll
2- Incorporate the dll dependency in CMAKE build system
 
- Some test input files are missing need to add them
- WASM syntax issues are coming like this one
```
unexpected character '\u{0}'
     --> <anon>:1:1 
```

### Steps to Reproduce

1. Clone this branch https://github.com/pkspyder007/metacall-core/tree/wasm-tests it contains some fixes to the wasm loader
2. Run Windows Test workflow on the branch

Note: The fixes in the branch are for the const expression required in creating arrays in C. [Fix](https://github.com/pkspyder007/metacall-core/blob/wasm-tests/source/loaders/wasm_loader/source/wasm_loader_function.c#L178:L180)
There a couple of places where this fix is made

**Comment by pkspyder007** [comment]
After adding the missing scripts from cmake to build output, new errors have popped

`dynlink_impl_interface_load_win32 | D:\a\metacall-core\metacall-core\source\dynlink\source\dynlink_impl_win32.c ] @Error : Failed to load: D:/a/metacall-core/metacall-core/build/Debug/wasm_loaderd.dll with error code [193]: %1 is not a valid Win32 application.`

[Link to CI logs ](https://github.com/pkspyder007/metacall-core/actions/runs/4980666020/jobs/8913864312)

The code changes can be found in  #431

**Comment by pkspyder007** [comment]
@viferga 

I have fixed the issue faced in the comment [here](https://github.com/metacall/core/pull/431#issuecomment-1549170086)

New segfault error are failing the tests 
```
Errors while running CTest
	 97 - metacall-wasm-test (SEGFAULT)
	 98 - metacall-wasm-python-port-test (SEGFAULT)
```
Github action [logs](https://github.com/pkspyder007/metacall-core/actions/runs/5009848587/jobs/8980035472)

The reason for undefined behavior is not found yet.

The changes done [here](https://github.com/metacall/core/pull/431/files#diff-f8ec6465da390632145d700a4193df8e6a193a59c97a360a7f634fb002c2081bR202-R212) might be a reason.
The macro provided by wasmtime `WASM_ARRAY_VEC` was not working correctly in initializing the `wasm_val_vec_t args_vec` this could be due to a recent upgrade to higher version.

One proposed solution is to add the arguments to the function implementation struct and use it from there and cleaning up the arguments memory part is hoisted  up to function cleanup. The arguments passed in the wasm loader are not allowed to be variadic, this check [here](https://github.com/metacall/core/blob/develop/source/loaders/wasm_loader/source/wasm_loader_function.c#LL162C23-L162C23) prevents that.

Also running build with sanitizer on locally causes all the test cases to fail
list of failed testcases - [link](https://pastebin.com/4jVtQsAA)
CTest logs - [link](https://pastebin.com/eyiDw47N)

**Comment by viferga** [comment]
Solved, the insights you have pointed out have been very useful.
