### ISSUE TITLE
Unable to build Metacall in MacOS 

### ISSUE THREAD

**Issue by fosslover69** [metacall/core#368]
While building Metacall from source in MacOS [this error](https://bin.cyberknight777.dev/OERc) is thrown. 
Current OS version: `MacOS Monterey (version 12.6.2)`
GCC version: `x86_64-apple-darwin21.6.0 `

**Comment by viferga** [comment]
We should implement the CI in MacOS (at least without languages) in order to avoid this kind of "dumb" errors. The bug is easy to solve but I have a queue of tasks to do before this, I will try to debug it asap.

**Comment by viferga** [comment]
This is solved.
