### ISSUE TITLE
Add Typescript Support to Windows CI Tests

### ISSUE THREAD

**Issue by pkspyder007** [metacall/core#372]
## 🐛 Bug Report

Currently the following languages are supported for windows CI tests - `python nodejs java` 
Adding TS to list will allow us to make the core more open to new contributors with more test coverage

While adding `ts` to the above mentioned list, it throws error during testing which are related to the dependencies not being copied properly to the build output directory
Here are the logs for the failed tests https://pastebin.com/Fp7MqZXx

This issue is similar to #362 which was solved in #364

**Comment by viferga** [comment]
Solved.
