### ISSUE TITLE
Build fail on MacOs

### ISSUE THREAD

**Issue by ashpect** [metacall/core#381]
## 🐛 Bug Report
While building for MacOS , the build fails while performing build step for funchook_detour_depends.

### Expected Behavior
The build should successfully get completed without throwing errors

### Current Behavior
Build Fails

### Possible Solution
Checking the funchook_detour_depends-build-err.log reveals the issue to be :
``` Undefined symbols for architecture arm64:
  "_funchook_os_syscall", referenced from:
      _funchook_os_open in os_func_unix.c.o
      _funchook_os_close in os_func_unix.c.o
      _funchook_os_read in os_func_unix.c.o
      _funchook_os_write in os_func_unix.c.o
      _funchook_os_mmap in os_func_unix.c.o
      _funchook_os_munmap in os_func_unix.c.o
      _funchook_os_mprotect in os_func_unix.c.o
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Possible solution can be to reroute miscalls via Rosetta for MacOs

### Steps to Reproduce in MacOS
1. Git clone the repo
2. mkdir core/build && cd core/build
3. cmake ..
4. cmake --build . --target install

### Detailed Description
![image](https://user-images.githubusercontent.com/93992470/216763783-f2edfc64-ba30-48ef-bcd7-c490e8bf275c.png)

**Comment by viferga** [comment]
I have updated the funchook version, check out the develop branch to see if it fails again. By the way I am gonna open an issue in Funchook. Are you using `clang` to compile?

**Comment by ashpect** [comment]
This issue was resolved after update to the latest funchook version.
