### ISSUE TITLE
Docker Backend Multi Arch

### ISSUE THREAD

**Issue by alberto98fx** [metacall/core#41]
It would be pretty awesome to have docker as a backend with exported Bash commands that gets ```pwd``` as variable and mount some core paths to guest to persist even when a new version is released. 

I.g 

```metacall pip3 install x``` 

Pip folder with installed modules should be available on guest in a path such as 

```/opt/metacall/pip``` 

and mounted via Docker run to the container.

**Comment by viferga** [comment]
The fallback install script to Docker has been implemented.

Shared volumes for Python and Logs are still not implemented, but **it needs testing**.

This is the new repo for providing a CLI image for the fallback:
https://github.com/metacall/cli

And here's the Docker Hub image:
https://hub.docker.com/repository/docker/metacall/cli

Now when trying to install in MacOs (not currently supported), it will prompt an error message and later on it will ask for installing the CLI with Docker:
`curl -sL https://raw.githubusercontent.com/metacall/install/master/install.sh | bash`
