### ISSUE TITLE
Empty buffer case for go port

### ISSUE THREAD

**Issue by iyear** [metacall/core#416]
## 🐛 Bug Report

When I was implementing the buffer type for the go port, a test case failed.

`goToValue`:
```go
if buf, ok := arg.(bytes.Buffer); ok {
	str := buf.String()
	p := unsafe.Pointer(C.CString(str))
	defer C.free(p)
	*ptr = C.metacall_value_create_buffer(p, (C.size_t)(len(str)))
	return
}
```

If we pass zero value of bytes.Buffer, ptr will equal nil. The question is, in `valueToGo`, how do we determine if this nil is a buffer type? We can't. So we need a solution to make even empty buffer correctly recognized by `valueToGo`.

### Expected Behavior

Correct handling of empty buffer

### Current Behavior

Returns nil when buffer is zero value.

### Possible Solution

1. Modify the port to use some special value such as `<nil>` instead of the empty buffer.
2. Modify core's judgment on empty buffer, but may create potential bugs.
https://github.com/metacall/core/blob/22af333f50829a0bc796e4ee72904a9779b5e002/source/reflect/source/reflect_value_type.c#L238-L246

**Comment by iyear** [comment]
I removed judgment for null buffer and recompiled core, it passed.

https://github.com/metacall/core/blob/22af333f50829a0bc796e4ee72904a9779b5e002/source/reflect/source/reflect_value_type.c#L240-L243

but I don't know if there are side effects.

**Comment by viferga** [comment]
https://github.com/metacall/core/commit/a87d68a19ca6816abdbf36392a5a4fc6b2536f67
