### ISSUE TITLE
The `node_loader` crashes when a Javascript Promise is rejected

### ISSUE THREAD

**Issue by devraymondsh** [metacall/core#419]
## 🐛 Bug Report

Let's say we have this code below with javascript:
```
async function my_async_function() {
   throw Error("Hi there!");
}
```

### Current Behavior
The Node loader crashes and the whole program stops.
```
/workspaces/metacall-core/source/ports/rs_port/tests/X/X.js
  throw Error("Hi there!");
        ^

Error: Hi there!
    at test_future_reject (/workspaces/metacall-core/source/ports/rs_port/tests/X/X.js)

Node.js v18.7.0
error: test failed, to rerun pass -p metacall --test return_type_test

Caused by:
  process didn't exit successfully: /workspaces/metacall-core/source/ports/rs_port/target/debug/deps/X X --exact --nocapture (exit status: 1)
```

### Expected Behavior
It is expected that Metacall stop the loader from crashing.

### Possible Solution
Adding a simple catch like below can be helpful:
```
function x() {
    my_async_function().catch(() => {});
}
```

**Comment by viferga** [comment]
@devraymondsh does this happen in `rs_port` only? I have not been able to reproduce it:

https://github.com/metacall/core/commit/b9e7146e8315131eee6362124ea2a34bb9541132#diff-ecc6ec7e3761645b3c6cb16ee2b0b04c35fe8b42f7089d497d16549b23802595R215

**Comment by devraymondsh** [comment]
One easy way to fix this is to add this handler anywhere in the code:
```js
process
  .on('unhandledRejection', (reason, p) => {
    // Or do something useful?
    console.error(reason, 'Unhandled Rejection at Promise', p);
  })
  .on('uncaughtException', (err) => {
    // Or do something useful?
    console.error(err, 'Uncaught Exception thrown');
  });
```

**Comment by devraymondsh** [comment]
The Metacall core team decided not to move forward with the issue and treat this as an expected behavior rather than a bug. That means, the core will match the behavior of the Nodejs runtime.
