### ISSUE TITLE
MVP Rust port for Metacall

### ISSUE THREAD

**Issue by swarnimarun** [metacall/core#42]
This issue is to list out things that may or may not have been completed in order to get rs-port working.

- [ ] Add the cargo based rs-port project. `// TODO: Will PR it when I can get cmake build working`
- [ ] Use [cmakeRust](https://github.com/Devolutions/CMakeRust)(might need some modifications) for the cmake build system integration.
- [ ] Setup cmake for the Rust project.

At the moment I haven't pushed the code because I haven't been able to get cmake working with any of it, but I just uploaded my source on [metacall-rs-port](https://github.com/swarnimarun/metacall-rs-port).

cc: @viferga

**Comment by viferga** [comment]
I will try to add a placeholder for your project, and merge it into master.
