### ISSUE TITLE
Clang Warning on macOS

### ISSUE THREAD

**Issue by ahmedihabb2** [metacall/core#427]
## 🐛 Bug Report

clang: warning: argument unused during compilation: '-fuse-ld=gold' [-Wunused-command-line-argument]

## View Full logs
[7_Build.txt](https://github.com/metacall/core/files/11326510/7_Build.txt)
Also here are the full CI logs on my own [fork](https://github.com/ahmedihabb2/core/actions/runs/4801549643/jobs/8543904406)

**Comment by viferga** [comment]
Solved
