### ISSUE TITLE
Unable to build metacall in Visual Studio 2019

### ISSUE THREAD

**Issue by roysti10** [metacall/core#430]
## 🐛 Bug Report

When building metacall in MSC 2019, getting the following error
`source/detours/funchook_detour/funchook/src/funchook/funchook.lib', needed by 'funchook_detourd.dll`
`source/tests/src/google-test-depends-build/lib/Debug/gtestd.lib', needed by 'preprocessor-testd.exe', missing and no known rule to make it`

### Expected Behavior
According to the cmake, funchook should be downloaded using `download.bat`, but the download is not happening
Gtest is not getting installed

### Possible Solution
Maybe can try to replace ExternalProject to FetchContest

### Steps to Reproduce
Build metacall in MSC 2019

###Temp solution
Disable fork security
Disable build tests

**Comment by viferga** [comment]
I think this has been solved or I have been not able to reproduce it anymore.
