### ISSUE TITLE
Implement Benchmarking CI

### ISSUE THREAD

**Issue by viferga** [metacall/core#441]
## 🚀 Feature

It would be pretty interesting to implement benchmarking CI and CD for knowing how code changes affect to the performance of metacall. For example, since more safety was added to NodeJS loader, after the version 0.3.x, the performance has been damaged a lot. We should be able to control this in a better way.

There's a tool that already integrates that and it is compatible with CTest and Google Tests: https://github.com/benchmark-action/github-action-benchmark

Here's the C++ Google Test version: https://github.com/benchmark-action/github-action-benchmark/tree/master/examples/cpp

It produces nice outputs and notifies if performance is degraded: https://benchmark-action.github.io/github-action-benchmark/dev/bench/

**Comment by ahmedihabb2** [comment]
Check this [PR ](https://github.com/metacall/core/pull/457)

**Comment by ahmedihabb2** [comment]
https://github.com/metacall/core/pull/457

**Comment by ahmedihabb2** [comment]
#457 Check this

**Comment by viferga** [comment]
This is implemented already.
