### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by durgesh077** [metacall/core#448]
## 🐛 Bug Report

whenever we use api
**https://dashboard.metacall.io/api/package/create**

```
{
runners:[]
jsons:[]
id:testing
type:application/zip
:[{"language_id":"node", "path":".","scripts":["./func2.js"]}]
}
```
as body (note: empty key name in json) we get segmentation fault and infinite loop
and if we use

```
{
runners:[]
jsons:[]
id:testing
type:application/zip
}
```
i.e removed empty key name
this doesn't have segmentation fault at least

### Expected Behavior
it should either throw error or deploy successfully

### Current Behavior
deploys infinitely

### Possible Solution

- can check faas implementation for create package api to handle black key name

### Steps to Reproduce
1. create a zip with some functions in js (say test.zip)
2. add metacall-node.json
3. try to deploy with  body given above

**Comment by durgesh077** [comment]
[test.zip.zip](https://github.com/metacall/core/files/11919462/test.zip.zip)

**Comment by viferga** [comment]
Solved.

https://github.com/metacall/core/commit/90adf3ec7c3bad4f467185bcff85981ae45fa322
