### ISSUE TITLE
Issue with java tests in windows

### ISSUE THREAD

**Issue by pkspyder007** [metacall/core#450]
## 🐛 Bug Report

Loading class definition from JAR file failing

Add class handles to metacall java_loader instead of throwing the following exception for e.g.
```
java.lang.ClassNotFoundException: src.JarTest.TesterJar2
```
or some error like thid
```
java.lang.NoSuchFieldException: signature
        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
        at bootstrap.getSignature(bootstrap.java:219)
        at bootstrap.java_bootstrap_discover_method_details(bootstrap.java:350)
java.lang.NoSuchFieldException: signature
        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
        at bootstrap.getSignature(bootstrap.java:219)
        at bootstrap.java_bootstrap_discover_method_details(bootstrap.java:350
```

### Steps to Reproduce
Build locally with Java support 
 
```
try {
    Class<?> c = clsLoader.loadClass(className);

    if (c != null) {
      handleList.add(c);
    }
  } catch (Exception ex) {
    // TODO: Implement better error handling
    System.out.println(ex);
}
```

**Comment by pkspyder007** [comment]
Working PR for Path fix and other insights
https://github.com/metacall/core/pull/449

**Comment by viferga** [comment]
Solved.

**Comment by praveen-quizizz** [comment]
@viferga can you please share the fixing PR here

**Comment by viferga** [comment]
This is the PR, it's mixed with other things because I was solving multiple bugs at the same time:
https://github.com/metacall/core/compare/c23999d05ee0c5c2382eefd280438c6b965f977b..803b6bd285e6e1144835c5bf9b082031ece7ec2b
