### ISSUE TITLE
Sandbox Plugin System Design

### ISSUE THREAD

**Issue by AhmedAlaa2024** [metacall/core#465]
## 🚀 Feature
# Sandbox Plugin System Design

## Description
Sandbox Plugin will provide a high-level API similar to Deno Permissions but with full control like in Docker containers. With this, any language like higher level ones like NodeJS, Ruby, Python.. will be able to control execution, especially for untrusted code. This also applies to any other supported language in MetaCall, like Rust, Java, C#

## APIs
- API Flag Format: --allow-{category} / --disallow-{category}

- Mapped Function Format: int sandbox_{category}(void *ctx, bool allow)

| Category             | Syscalls Affected       |
|----------------------|-------------------------|
| [io](#io)                   | [read](#read) - [write](#write) - [open](#open) - [close](#close) - [lseek](#lseek) - [dup](#dup) - [dup2](#dup2) - [pipe](#pipe) - [select](#select) - [poll](#poll) - [epoll](#epoll) - [fcntl](#fcntl) - [ioctl](#ioctl) - [pread](#pread) - [pwrite](#pwrite) - [readv](#readv) - [writev](#writev) - [send](#send) - [recv](#recv) - [sendto](#sendto) - [recvfrom](#recvfrom) - [sendmsg](#sendmsg) - [recvmsg](#recvmsg) - [fsync](#fsync) - [fdatasync](#fdatasync) |
| [sockets](#sockets)              | [socket](#socket) - [bind](#bind) - [listen](#listen) - [accept](#accept) - [connect](#connect) - [send](#send) - [recv](#recv) - [sendto](#sendto) - [recvfrom](#recvfrom) - [shutdown](#shutdown) - [getsockname](#getsockname) - [getpeername](#getpeername) - [socketpair](#socketpair) - [setsockopt](#setsockopt) - [getsockopt](#getsockopt) - [select](#select) - [poll](#poll) - [epoll](#epoll) - [fcntl](#fcntl) - [ioctl](#ioctl) - [getaddrinfo](#getaddrinfo) - [getnameinfo](#getnameinfo) - [gethostname](#gethostname) - [gethostbyname](#gethostbyname) - [gethostbyaddr](#gethostbyaddr) |
| [ipc](#ipc)                  | [shmget](#shmget) - [shmat](#shmat) - [shmdt](#shmdt) - [shmctl](#shmctl) - [msgget](#msgget) - [msgsnd](#msgsnd) - [msgrcv](#msgrcv) - [msgctl](#msgctl) - [semget](#semget) - [semop](#semop) - [semctl](#semctl) - [ftok](#ftok) |
| [process](#process)            | [fork](#fork) - [vfork](#vfork) - [clone](#clone) - [exec](#exec) - [wait](#wait) - [waitpid](#waitpid) - [waitid](#waitid) - [exit](#exit) - [exit_group](#exit_group) - [kill](#kill) - [getpid](#getpid) - [getppid](#getppid) - [setsid](#setsid) - [setpgid](#setpgid) - [nice](#nice) - [sched_yield](#sched_yield) - [setpriority](#setpriority) - [getpriority](#getpriority) - [getpgid](#getpgid) - [setsid](#setsid) |
| [filesystems](#filesystems)            | [open](#open) - [close](#close) - [read](#read) - [write](#write) - [lseek](#lseek) - [unlink](#unlink) - [mkdir](#mkdir) - [rmdir](#rmdir) - [rename](#rename) - [link](#link) - [symlink](#symlink) - [stat](#stat) - [fstat](#fstat) - [lstat](#lstat) - [chmod](#chmod) - [newfstatat](#newfstatat) - [chown](#chown) - [utime](#utime) - [access](#access) - [truncate](#truncate) - [ftruncate](#ftruncate) - [sync](#sync) - [fsync](#fsync) - [fdatasync](#fdatasync) - [chdir](#chdir) - [getcwd](#getcwd) - [opendir](#opendir) - [readdir](#readdir) - [closedir](#closedir) - [chroot](#chroot) - [mount](#mount) - [umount](#umount) |
| [time](#time)            | [time](#time) - [gettimeofday](#gettimeofday) - [clock_gettime](#clock_gettime) - [clock_settime](#clock_settime) - [clock_getres](#clock_getres) - [date](#date) |
| [memory](#memory)            | [mmap](#mmap) - [munmap](#munmap) - [mprotect](#mprotect) - [brk](#brk) - [sbrk](#sbrk) - [sbrk](#sbrk) - [mincore](#mincore) - [madvise](#madvise) - [posix_memalign](#posix_memalign) - [malloc](#malloc) - [calloc](#calloc) - [realloc](#realloc) - [free](#free) - [mlock](#mlock) - [munlock](#munlock) - [mlockall](#mlockall) - [munlockall](#munlockall) - [getrlimit](#getrlimit) - [setrlimit](#setrlimit) - [getrusage](#getrusage) - [getpagesize](#getpagesize) |
| [signals](#signals)            | [signal](#signal) - [sigaction](#sigaction) - [kill](#kill) - [raise](#raise) - [abort](#abort) - [pause](#pause) - [sigpending](#sigpending) - [sigprocmask](#sigprocmask) - [sigsuspend](#sigsuspend) - [sigqueue](#sigqueue) - [sigsetjmp](#sigsetjmp) - [siglongjmp](#siglongjmp) - [sigaltstack](#sigaltstack) - [signalfd](#signalfd) |

### <a id="io"></a>I/O (Input/Output):
    I/O system calls in Linux enable processes to read from and write to various input and output devices, including files, network sockets, and terminals. These calls allow data to be transferred between the program and external resources.

1. <a id="read"></a><span style="color: green;">**read**</span>: Reads data from a file descriptor into a buffer.
2. <a id="write"></a><span style="color: green;">**write**</span>: Writes data from a buffer to a file descriptor.
3. <a id="open"></a><span style="color: green;">**open**</span>: Opens a file or creates a new one.
4. <a id="close"></a><span style="color: green;">**close**</span>: Closes a file descriptor.
5. <a id="lseek"></a><span style="color: green;">**lseek**</span>: Changes the file position of a file descriptor.
6. <a id="dup"></a><span style="color: green;">**dup**</span>: Duplicates a file descriptor.
7. <a id="dup2"></a><span style="color: green;">**dup2**</span>: Duplicates a file descriptor to a specified target file descriptor.
8. <a id="pipe"></a><span style="color: green;">**pipe**</span>: Creates an interprocess communication (IPC) pipe.
9. <a id="select"></a><span style="color: green;">**select**</span>: Monitors multiple file descriptors for read, write, or error conditions.
10. <a id="poll"></a><span style="color: green;">**poll**</span>: Similar to select, monitors multiple file descriptors for events.
11. <a id="epoll"></a><span style="color: green;">**epoll**</span>: Provides a scalable and more efficient mechanism for monitoring file descriptors.
12. <a id="fcntl"></a><span style="color: green;">**fcntl**</span>: Performs various operations on file descriptors.
13. <a id="ioctl"></a><span style="color: green;">**ioctl**</span>: Performs I/O control operations on devices or sockets.
14. <a id="pread"></a><span style="color: green;">**pread**</span>: Reads data from a file descriptor at a specific offset without changing the file position.
15. <a id="pwrite"></a><span style="color: green;">**pwrite**</span>: Writes data to a file descriptor at a specific offset without changing the file position.
16. <a id="readv"></a><span style="color: green;">**readv**</span>: Reads data into multiple buffers from a file descriptor.
17. <a id="writev"></a><span style="color: green;">**writev**</span>: Writes data from multiple buffers to a file descriptor.
18. <a id="send"></a><span style="color: green;">**send**</span>: Sends data on a connected socket.
19. <a id="recv"></a><span style="color: green;">**recv**</span>: Receives data from a connected socket.
20. <a id="sendto"></a><span style="color: green;">**sendto**</span>: Sends data to a specified address and port on a socket.
21. <a id="recvfrom"></a><span style="color: green;">**recvfrom**</span>: Receives data from a socket, including the sender's address and port.
22. <a id="sendmsg"></a><span style="color: green;">**sendmsg**</span>: Sends a message on a socket with greater control over headers and data.
23. <a id="recvmsg"></a><span style="color: green;">**recvmsg**</span>: Receives a message from a socket with control information.
24. <a id="fsync"></a><span style="color: green;">**fsync**</span>: Synchronizes a file's in-memory state with its on-disk state.
25. <a id="fdatasync"></a><span style="color: green;">**fdatasync**</span>: Synchronizes only the data part of a file with its on-disk state.

### <a id="sockets"></a>Sockets:
    Socket system calls provide the foundation for network communication in Linux. They allow processes to create, connect, send, and receive data over network sockets, facilitating communication between processes across different devices or even over a network.

1. <a id="socket"></a><span style="color: green;">socket</span>: Creates a new socket.
2. <a id="bind"></a><span style="color: green;">bind</span>: Associates a socket with a specific address and port.
3. <a id="listen"></a><span style="color: green;">listen</span>: Puts a socket into listening mode for incoming connections (used with server sockets).
4. <a id="accept"></a><span style="color: green;">accept</span>: Accepts an incoming connection on a listening socket.
5. <a id="connect"></a><span style="color: green;">connect</span>: Initiates a connection to a remote socket.
6. <a id="send"></a><span style="color: green;">send</span>: Sends data on a connected socket.
7. <a id="recv"></a><span style="color: green;">recv</span>: Receives data from a connected socket.
8. <a id="sendto"></a><span style="color: green;">sendto</span>: Sends data to a specified address and port on a socket.
9. <a id="recvfrom"></a><span style="color: green;">recvfrom</span>: Receives data from a socket, including the sender's address and port.
10. <a id="shutdown"></a><span style="color: green;">shutdown</span>: Shuts down part or all of a socket's communication.
11. <a id="getsockname"></a><span style="color: green;">getsockname</span>: Retrieves the local address and port of a socket.
12. <a id="getpeername"></a><span style="color: green;">getpeername</span>: Retrieves the remote address and port of a connected socket.
13. <a id="socketpair"></a><span style="color: green;">socketpair</span>: Creates a pair of connected sockets for local interprocess communication (IPC).
14. <a id="setsockopt"></a><span style="color: green;">setsockopt</span>: Sets options on a socket.
15. <a id="getsockopt"></a><span style="color: green;">getsockopt</span>: Retrieves options from a socket.
16. <a id="select"></a><span style="color: green;">select</span>: Monitors multiple sockets for read, write, or error conditions.
17. <a id="poll"></a><span style="color: green;">poll</span>: Similar to select, monitors multiple sockets for events.
18. <a id="epoll"></a><span style="color: green;">epoll</span>: Provides a scalable and more efficient mechanism for monitoring sockets.
19. <a id="fcntl"></a><span style="color: green;">fcntl</span>: Performs various operations on socket file descriptors.
20. <a id="ioctl"></a><span style="color: green;">ioctl</span>: Performs I/O control operations on sockets.
21. <a id="getaddrinfo"></a><span style="color: green;">getaddrinfo</span>: Resolves hostnames and service names to socket addresses.
22. <a id="getnameinfo"></a><span style="color: green;">getnameinfo</span>: Retrieves human-readable information from socket addresses.
23. <a id="gethostname"></a><span style="color: green;">gethostname</span>: Retrieves the name of the local host.
24. <a id="gethostbyname"></a><span style="color: green;">gethostbyname</span>: Retrieves host information based on a hostname (deprecated, use getaddrinfo instead).
25. <a id="gethostbyaddr"></a><span style="color: green;">gethostbyaddr</span>: Retrieves host information based on an IP address (deprecated, use getaddrinfo instead).

### <a id="ipc"></a>IPC (Interprocess Communication):
    IPC system calls enable processes to exchange data and synchronize their actions. This category includes shared memory, message queues, and semaphores, which facilitate communication and coordination between different processes running on the same system.

1. <a id="shmget"></a><span style="color: green;">shmget</span>: Allocates a shared memory segment.
2. <a id="shmat"></a><span style="color: green;">shmat</span>: Attaches a shared memory segment to the calling process's address space.
3. <a id="shmdt"></a><span style="color: green;">shmdt</span>: Detaches a shared memory segment from the calling process.
4. <a id="shmctl"></a><span style="color: green;">shmctl</span>: Performs control operations on a shared memory segment.
5. <a id="msgget"></a><span style="color: green;">msgget</span>: Allocates a new message queue.
6. <a id="msgsnd"></a><span style="color: green;">msgsnd</span>: Sends a message to a message queue.
7. <a id="msgrcv"></a><span style="color: green;">msgrcv</span>: Receives a message from a message queue.
8. <a id="msgctl"></a><span style="color: green;">msgctl</span>: Performs control operations on a message queue.
9. <a id="semget"></a><span style="color: green;">semget</span>: Allocates a new set of semaphores.
10. <a id="semop"></a><span style="color: green;">semop</span>: Performs semaphore operations (e.g., wait, signal) on a semaphore set.
11. <a id="semctl"></a><span style="color: green;">semctl</span>: Performs control operations on a semaphore set.
12. <a id="ftok"></a><span style="color: green;">ftok</span>: Generates a key for interprocess communication resources.

### <a id="process"></a>Process Management:
    Process management system calls are crucial for creating, controlling, and managing processes. These calls include process creation, termination, signal handling, and resource management, allowing processes to interact and coordinate their activities.

1. <a id="fork"></a><span style="color: green;">fork</span>: Creates a new process by duplicating the calling process.
2. <a id="vfork"></a><span style="color: green;">vfork</span>: Creates a new process, but suspends the parent process until the child process terminates.
3. <a id="clone"></a><span style="color: green;">clone</span>: Creates a new process or thread, allowing for more fine-grained control than fork.
4. <a id="exec"></a><span style="color: green;">exec</span>: Replaces the current process image with a new one.
5. <a id="wait"></a><span style="color: green;">wait</span>: Waits for a child process to terminate and collects its exit status.
6. <a id="waitpid"></a><span style="color: green;">waitpid</span>: Waits for a specific child process to terminate and collects its exit status.
7. <a id="waitid"></a><span style="color: green;">waitid</span>: Waits for the termination of a specific process or group of processes.
8. <a id="exit"></a><span style="color: green;">exit</span>: Terminates the calling process and returns an exit status to the parent process.
9. <a id="exit_group"></a><span style="color: green;">exit_group</span>: Terminates all threads in the calling process and exits the process group.
10. <a id="kill"></a><span style="color: green;">kill</span>: Sends a signal to a specified process or process group.
11. <a id="getpid"></a><span style="color: green;">getpid</span>: Retrieves the process ID (PID) of the calling process.
12. <a id="getppid"></a><span style="color: green;">getppid</span>: Retrieves the parent process's PID of the calling process.
13. <a id="setsid"></a><span style="color: green;">setsid</span>: Creates a new session and sets the calling process as the session leader.
14. <a id="setpgid"></a><span style="color: green;">setpgid</span>: Sets the process group ID of a specified process.
15. <a id="nice"></a><span style="color: green;">nice</span>: Adjusts the scheduling priority of a process.
16. <a id="sched_yield"></a><span style="color: green;">sched_yield</span>: Yields the CPU to other processes in the same priority range.
17. <a id="setpriority"></a><span style="color: green;">setpriority</span>: Sets the scheduling priority of a process.
18. <a id="getpriority"></a><span style="color: green;">getpriority</span>: Retrieves the scheduling priority of a process.
19. <a id="getpgid"></a><span style="color: green;">getpgid</span>: Retrieves the process group ID of a process.
20. <a id="setsid"></a><span style="color: green;">setsid</span>: Creates a new session and sets the calling process as the session leader.

### <a id="filesystems"></a>File Systems:
    File system system calls provide the means to interact with the file system, including file and directory creation, manipulation, and access control. These calls allow processes to read, write, and manage files and directories on storage devices.

1. <a id="open"></a><span style="color: green;">open</span>: Opens a file or creates a new one.
2. <a id="close"></a><span style="color: green;">close</span>: Closes a file descriptor.
3. <a id="read"></a><span style="color: green;">read</span>: Reads data from a file descriptor into a buffer.
4. <a id="write"></a><span style="color: green;">write</span>: Writes data from a buffer to a file descriptor.
5. <a id="lseek"></a><span style="color: green;">lseek</span>: Changes the file position of a file descriptor.
6. <a id="unlink"></a><span style="color: green;">unlink</span>: Removes a directory entry or a file.
7. <a id="mkdir"></a><span style="color: green;">mkdir</span>: Creates a new directory.
8. <a id="rmdir"></a><span style="color: green;">rmdir</span>: Removes a directory.
9. <a id="rename"></a><span style="color: green;">rename</span>: Renames a file or directory.
10. <a id="link"></a><span style="color: green;">link</span>: Creates a hard link to an existing file.
11. <a id="symlink"></a><span style="color: green;">symlink</span>: Creates a symbolic link to a file.
12. <a id="stat"></a><span style="color: green;">stat</span>: Retrieves file status information.
13. <a id="fstat"></a><span style="color: green;">fstat</span>: Retrieves file status information for an open file.
14. <a id="lstat"></a><span style="color: green;">lstat</span>: Retrieves symbolic link status information.
15. <a id="chmod"></a><span style="color: green;">chmod</span>: Changes the permissions of a file or directory.
16. <a id="newfstatat"></a><span style="color: green;">newfstatat</span>: Retrieves file status information relative to a directory file descriptor.
17. <a id="chown"></a><span style="color: green;">chown</span>: Changes the ownership of a file or directory.
18. <a id="utime"></a><span style="color: green;">utime</span>: Sets access and modification times for a file.
19. <a id="access"></a><span style="color: green;">access</span>: Checks accessibility of a file.
20. <a id="truncate"></a><span style="color: green;">truncate</span>: Truncates a file to a specified length.
21. <a id="ftruncate"></a><span style="color: green;">ftruncate</span>: Truncates an open file to a specified length.
22. <a id="sync"></a><span style="color: green;">sync</span>: Synchronizes cached writes to persistent storage.
23. <a id="fsync"></a><span style="color: green;">fsync</span>: Synchronizes a file's in-memory state with its on-disk state.
24. <a id="fdatasync"></a><span style="color: green;">fdatasync</span>: Synchronizes only the data part of a file with its on-disk state.
25. <a id="chdir"></a><span style="color: green;">chdir</span>: Changes the current working directory.
26. <a id="getcwd"></a><span style="color: green;">getcwd</span>: Retrieves the current working directory.
27. <a id="opendir"></a><span style="color: green;">opendir</span>: Opens a directory for reading.
28. <a id="readdir"></a><span style="color: green;">readdir</span>: Reads the next entry from a directory.
29. <a id="closedir"></a><span style="color: green;">closedir</span>: Closes a directory.
30. <a id="chroot"></a><span style="color: green;">chroot</span>: Changes the root directory for a process.
31. <a id="mount"></a><span style="color: green;">mount</span>: Mounts a file system.
32. <a id="umount"></a><span style="color: green;">umount</span>: Unmounts a file system.

### <a id="time"></a>Date and Time:
    Date and time system calls allow processes to work with time-related information. These calls include functions for retrieving the current time, setting timers, and manipulating time values, helping programs manage timestamps and schedule events.

1. <a id="time"></a><span style="color: green;">time</span>: Retrieves the current time since the Epoch.
2. <a id="gettimeofday"></a><span style="color: green;">gettimeofday</span>: Retrieves the current time with microsecond precision.
3. <a id="clock_gettime"></a><span style="color: green;">clock_gettime</span>: Retrieves the current time based on a specified clock.
4. <a id="clock_settime"></a><span style="color: green;">clock_settime</span>: Sets the time of a specified clock.
5. <a id="clock_getres"></a><span style="color: green;">clock_getres</span>: Retrieves the resolution of a specified clock.
6. <a id="date"></a><span style="color: green;">date</span>: Displays or sets the system date and time.
7. <a id="sleep"></a><span style="color: green;">sleep</span>: Suspends the execution of a process for a specified number of seconds.
8. <a id="usleep"></a><span style="color: green;">usleep</span>: Suspends the execution of a process for a specified number of microseconds.
9. <a id="nanosleep"></a><span style="color: green;">nanosleep</span>: Suspends the execution of a process for a specified number of nanoseconds.
10. <a id="clock_nanosleep"></a><span style="color: green;">clock_nanosleep</span>: Suspends the execution of a process until a specified clock time is reached, with nanosecond precision.

### <a id="memory"></a>Memory Management:
    Memory management system calls deal with the allocation, deallocation, and manipulation of memory in a process's address space. They include functions for memory mapping, memory protection, dynamic memory allocation, and memory locking.

1. <a id="mmap"></a><span style="color: green;">mmap</span>: Maps files or devices into memory.
2. <a id="munmap"></a><span style="color: green;">munmap</span>: Unmaps files or devices from memory.
3. <a id="mprotect"></a><span style="color: green;">mprotect</span>: Changes the protection of memory regions.
4. <a id="brk"></a><span style="color: green;">brk</span>: Sets the end of the data (heap) segment.
5. <a id="sbrk"></a><span style="color: green;">sbrk</span>: Increases or decreases the program's data space.
6. <a id="mincore"></a><span style="color: green;">mincore</span>: Determines whether pages are resident in memory.
7. <a id="madvise"></a><span style="color: green;">madvise</span>: Provides advice about memory use.
8. <a id="posix_memalign"></a><span style="color: green;">posix_memalign</span>: Allocates aligned memory.
9. <a id="malloc"></a><span style="color: green;">malloc</span>: Allocates memory.
10. <a id="calloc"></a><span style="color: green;">calloc</span>: Allocates and initializes memory.
11. <a id="realloc"></a><span style="color: green;">realloc</span>: Changes the size of allocated memory.
12. <a id="free"></a><span style="color: green;">free</span>: Frees allocated memory.
13. <a id="mlock"></a><span style="color: green;">mlock</span>: Locks memory into RAM.
14. <a id="munlock"></a><span style="color: green;">munlock</span>: Unlocks memory locked with mlock.
15. <a id="mlockall"></a><span style="color: green;">mlockall</span>: Locks all current and future pages into RAM.
16. <a id="munlockall"></a><span style="color: green;">munlockall</span>: Unlocks all locked pages.
17. <a id="getrlimit"></a><span style="color: green;">getrlimit</span>: Gets resource limits.
18. <a id="setrlimit"></a><span style="color: green;">setrlimit</span>: Sets resource limits.
19. <a id="getrusage"></a><span style="color: green;">getrusage</span>: Gets resource usage statistics.
20. <a id="getpagesize"></a><span style="color: green;">getpagesize</span>: Gets the system page size.

### <a id="signals"></a>Signal Handling:
    Signal handling system calls are essential for managing asynchronous notifications, known as signals, sent to processes. These calls allow processes to establish signal handlers, send signals to other processes, and respond to specific events or exceptions, ensuring proper error handling and process coordination.

1. <a id="signal"></a><span style="color: green;">signal</span>: Sets a function to handle a signal.
2. <a id="sigaction"></a><span style="color: green;">sigaction</span>: Examines and modifies signal action.
3. <a id="kill"></a><span style="color: green;">kill</span>: Sends a signal to a process.
4. <a id="raise"></a><span style="color: green;">raise</span>: Sends a signal to the calling process.
5. <a id="abort"></a><span style="color: green;">abort</span>: Terminates the calling process.
6. <a id="pause"></a><span style="color: green;">pause</span>: Suspends the calling process until a signal is received.
7. <a id="sigpending"></a><span style="color: green;">sigpending</span>: Gets the set of blocked signals.
8. <a id="sigprocmask"></a><span style="color: green;">sigprocmask</span>: Examines and modifies the signal mask.
9. <a id="sigsuspend"></a><span style="color: green;">sigsuspend</span>: Replaces the signal mask and suspends the process.
10. <a id="sigqueue"></a><span style="color: green;">sigqueue</span>: Sends a signal with data to a process.
11. <a id="sigsetjmp"></a><span style="color: green;">sigsetjmp</span>: Saves the calling environment for later use with siglongjmp.
12. <a id="siglongjmp"></a><span style="color: green;">siglongjmp</span>: Restores the environment saved by sigsetjmp and returns control.
13. <a id="sigaltstack"></a><span style="color: green;">sigaltstack</span>: Sets an alternative signal stack.
14. <a id="signalfd"></a><span style="color: green;">signalfd</span>: Creates a file descriptor for signals.

## Issues to be considered
1. Is seccomp filters affect the caller process only or the children too?
2. You should ensure the security for the sandbox plugin to prevent anyone from disabling or missing the sandbox source code.

## Todo
1. Add the user management system calls to the table.
2. Implement the APIs using ext_loader.
4. Provide security for the sandbox plugin directory.
5. Write test suites for all the APIs and check all the common functions in different languages.

## Resources
1. You can find all the provided system calls by Linux kernel [here](https://github.com/seccomp/libseccomp/blob/main/include/seccomp-syscalls.h).

6. For inspiration, you can look at [Seccomp Security Profiles for Docker](https://docs.docker.com/engine/security/seccomp/)

7. For more inspiration, you can look at [Runtime privilege and Linux capabilities](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities).

8. Like the previous resource, This is a similar approach for Seccomp called [Capabilities](https://dockerlabs.collabnix.com/advanced/security/capabilities/) introduced by Docker. But don't forget we are working on "Seccomp" approach.

9. For more and more inspiration, you can look at [Deno's Permissions](https://docs.deno.com/runtime/manual/basics/permissions)

**Comment by viferga** [comment]
This is finished, we should use this post to document the sandbox plugin, maybe also extend the cli_sandbox_plugin adding more options to metacallcli.
