### ISSUE TITLE
feat: Pass include directory for Python headers

### ISSUE THREAD

**Issue by FirePing32** [metacall/core#475]
### Is your feature request related to a problem? 
The brew formula for metacall fails to build partly, as it could not find Python headers to build the Python loader. See https://github.com/metacall/homebrew/issues/4 for full backtrace.

### Describe the solution you'd like
Allow the user to pass an optional argument/flag to `cmake` containing the correct location of Python headers.

### Additional context 
Platform: intel/AMD64
OS: MacOS Ventura 13.5

**Comment by FirePing32** [comment]
cc @giarve @viferga

**Comment by viferga** [comment]
Solved: https://github.com/metacall/core/blob/d70f10ad66fc02f42e3f6b0a28c50f176331a1ce/tools/metacall-configure.sh#L235
