### ISSUE TITLE
Setup workflow dispatch in Actions for metacall/homebrew

### ISSUE THREAD

**Issue by FirePing32** [metacall/core#497]
## 🚀 Feature

Setup a workflow dispatch event in the current CI to trigger tests and generate binaries for https://github.com/metacall/homebrew.

### Is your feature request related to a problem? 
Currently all releases are manually created in https://github.com/metacall/homebrew, which requires updating the shasum hash and metacall version. This feature will run a CI workflow to update the brew formula through [workflow dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch).

### Describe the solution you'd like
A solution implemented [here](https://github.com/orgs/community/discussions/26323#discussioncomment-3251448) can be discussed.

Also fixes: https://github.com/metacall/homebrew/issues/8

**Comment by viferga** [comment]
We have started to implement this, but this is only the first step.

In the distributable and homebrew side, we should verify that the lastest version tag and master works with the distributable, if it passes when using a tag, it should update the version, do a commit and release.

This work is still not done but it will. Here's the base workflow: https://github.com/metacall/core/blob/develop/.github/workflows/distributable-dispatch.yml

@haggyyy2002 We forgot to update the homebrew too.
