### ISSUE TITLE
Bug: argv issue while running metacall-deploy with metacall runtime

### ISSUE THREAD

**Issue by aakritiawasthi** [metacall/core#506]
## 🐛 Bug Report

[metacall/install#23](https://github.com/metacall/install/issues/23)

When we execute metacall-deploy with the metacall runtime, it throws a warning like:

```! 0x223eb60, 0x7f8c8d873e00 does not exists as a valid command.```

### Expected Behavior
metacall-deploy should have been able to parse the argv (--version) and should have returned the version of metacall-deploy.

### Current Behavior
metacall-deploy is taking some pointers as argv which is not an expected behaviour

### Steps to Reproduce
1. Install @metacall/deploy somewhere inside /gnu/lib using ```metacall npm i -g --prefix=/gnu/lib/some_folder @metacall/deploy```
2. Execute @metacall/deploy dist/index.js with metacall runtime like below

```metacall /gnu/lib/.metacall/lib/node_modules/@metacall/deploy/dist/index.js --version```

### Context (Environment)
Operating System -> MintOS (Linux)

**Comment by viferga** [comment]
@aakritiawasthi thanks for reporting, I have solved this bug in the last commit on my PR: https://github.com/metacall/core/pull/504

I will merge this into develop and tag a new version as soon as possible.
