### ISSUE TITLE
packages issue in rpc and backtrace in metacall-runtime.sh

### ISSUE THREAD

**Issue by ashpect** [metacall/core#511]
## 🐛 Bug Report

The rpc argument which installs libcurl4 and holds it fails during the execution of metacall-runtime.sh
<img width="1089" alt="Screenshot 2024-06-19 at 2 34 50 PM" src="https://github.com/metacall/core/assets/93992470/78da9f6a-ef64-476b-aa10-a0d36b0a3257">

### Expected Behavior
metacall:core/runtime builds

### Current Behavior
runtime image fails to builds

### Detailed Description
I also commented/removed the rpc and the backtrace failed..removing both of them successfully build the image so the issue the only limited to the 2 packages. The below is when rpc was removed with backtrace enabled.
![image](https://github.com/metacall/core/assets/93992470/409b989a-325f-4135-b174-f4a085265acd)
![image](https://github.com/metacall/core/assets/93992470/2d6b5d00-c280-4d3e-93e5-087d597a867f)

**Comment by viferga** [comment]
This is solved here: https://github.com/metacall/core/pull/504/commits/500f2b1a3188001ab55a34f6bb1230c98feecb10
