### ISSUE TITLE
Exporting in the node port

### ISSUE THREAD

**Issue by HeeManSu** [metacall/core#518]
Exporting in the node port to solve the issue in the call endpoint of FaaS implementation

https://github.com/metacall/core/blob/4d621a0269d604ea626811b72d3d5dae691b69a3/source/metacall/include/metacall/metacall.h#L1139

**Comment by viferga** [comment]
https://github.com/metacall/core/commit/649a0546a42ee638ca68ee0d470c6ea4e3bdeb3e
