### ISSUE TITLE
Ruby C API error handling

### ISSUE THREAD

**Issue by giarve** [metacall/core#61]
Currently class static method calls and object method calls are not properly handling errors.
If there's an uncaught exception in Ruby, the program will terminate (segfault).

See issue #53

To solve this, rb_protect must be used:
https://silverhammermba.github.io/emberb/c/#rb_protect

**Comment by viferga** [comment]
We have added rb_protect to the invokations, I think it should be enough for now, but we should improve this eventually. Let's do it on demand, whenever someone finds a segmentation fault. We have stack unwinding so we can localize the call and rb_protect it when needed.
