### ISSUE TITLE
Awaiting future values

### ISSUE THREAD

**Issue by Tabzz98** [metacall/core#75]
It would be helpful to have a function such as `metacall_await_future` in the C API for awaiting future values. 

This can lift the need for introspecting loaded functions to know if they're `async`. `metacallv_s` (or other calling functions) could return a future value (with `metacall_value_id` 12) which could then be converted to the calling language's future type using `metacall_await_future`. No additional  abstractions would be needed in order to handle `async` functions in MetaCall ports.

**Comment by viferga** [comment]
https://github.com/metacall/core/commit/a3b29308e30f539fcaf2068a8ca001bba8beea47
https://github.com/metacall/core/commit/44a43d63b73fc2c306e723cacbd81e31a777a397
Done.
