### ISSUE TITLE
documentation changes

### ISSUE THREAD

**Issue by krush11** [metacall/core#77]
- [metacall/core](https://github.com/metacall/core) has Travis-ci integrated. There could be a badge added to README.md
- [.github/ISSUE_TEMPLATE](https://github.com/metacall/core/blob/develop/.github/ISSUE_TEMPLATE.md) and [.github/PULL_REQUEST_TEMPLATE](https://github.com/metacall/core/blob/develop/.github/PULL_REQUEST_TEMPLATE.md) are blank and need to be set

@giarve please check if these changes can be added to `develop`

**Comment by viferga** [comment]
We already have badges (although they are outdated), you can create a new PR and add those badges there:
https://github.com/metacall/core/tree/develop/docs#7-platform-support

Take into account that we have three pipelines right now:
![2021-03-10-071332_1920x1017_scrot](https://user-images.githubusercontent.com/7854099/110635106-59eda980-8170-11eb-9c1b-d3821093b3e2.png)

- Docker is the builds for metacall/core on DockerHub.
- TravisCI is for publishing the artifacts.
- And GitLab CI is a mirror of Travis.

Related to the templates, it would be better if you can extend them. Check examples of other repositories which have an active community.
