### ISSUE TITLE
Unable to compile source with cmake

### ISSUE THREAD

**Issue by samarthpusalkar** [metacall/core#88]
When trying to compile with the latest version of cmake (3.20.0) it gives the following errors and warnings:

CMake Error at CMakeLists.txt:31 (string):
  string no output variable specified

CMake Warning (dev) at CMakeLists.txt:81 (add_definitions):
  Policy CMP0005 is not set: Preprocessor definition values are now escaped
  automatically.  Run "cmake --help-policy CMP0005" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:81 (add_definitions):
  Policy CMP0005 is not set: Preprocessor definition values are now escaped
  automatically.  Run "cmake --help-policy CMP0005" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:81 (add_definitions):
  Policy CMP0005 is not set: Preprocessor definition values are now escaped
  automatically.  Run "cmake --help-policy CMP0005" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:81 (add_definitions):
  Policy CMP0005 is not set: Preprocessor definition values are now escaped
  automatically.  Run "cmake --help-policy CMP0005" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:81 (add_definitions):
  Policy CMP0005 is not set: Preprocessor definition values are now escaped
  automatically.  Run "cmake --help-policy CMP0005" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Lib version
CMake Error at version/CMakeLists.txt:21 (include):
  include could not find requested file:

    Warnings

CMake Error at version/CMakeLists.txt:27 (include):
  include could not find requested file:

    SecurityFlags

CMake Error at version/CMakeLists.txt:33 (string):
  string no output variable specified

CMake Error at version/CMakeLists.txt:34 (string):
  string no output variable specified

CMake Error at version/CMakeLists.txt:57 (source_group_by_path):
  Unknown CMake command "source_group_by_path".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.20)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by viferga** [comment]
Are you doing this from command line or with CMake GUI? How are you setting the paths?
![2021-03-16-134533_1920x1080_scrot](https://user-images.githubusercontent.com/7854099/111311191-e8a86d80-862b-11eb-8c3b-b0b9c597b4b3.png)

I have the project root in `E:/` it is a shared folder.

**Comment by samarthpusalkar** [comment]
I tried with both GUI and command line
source                         C:/Users/sampu/Documents/core/source
build the binaries        C:/Users/sampu/Documents/metacall

**Comment by viferga** [comment]
The source path is this: `C:/Users/sampu/Documents/core/`
And the binaries must go in some place like: `C:/Users/sampu/Documents/core/build`
I think you have to create the second folder before running CMake.

**Comment by viferga** [comment]
Tell me if this solves your problem, so I can close the issue.

**Comment by samarthpusalkar** [comment]
I was successfully able to compile but it gave the following warnings:

CMake Warning (dev) at CMakeLists.txt:35 (include):
  Policy CMP0120 is not set: The WriteCompilerDetectionHeader module is
  removed.  Run "cmake --help-policy CMP0120" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.20/Modules/WriteCompilerDetectionHeader.cmake:255 (message):
  The WriteCompilerDetectionHeader module will be removed by policy CMP0120.
  Projects should be ported away from the module, perhaps by bundling a copy
  of the generated header or using a third-party alternative.
Call Stack (most recent call first):
  CMakeLists.txt:35 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
