### ISSUE TITLE
Add Issue + PR Templates

### ISSUE THREAD

**Issue by HarshCasper** [metacall/core#89]
## Description 

As discussed with @josead we would be adding some Issues + PR templates for making the Contribution Workflow better. 

cc: @viferga

**Comment by Siddhant-K-code** [comment]
@HarshCasper will you gonna work upon it? or I can work on this issue :)

**Comment by HarshCasper** [comment]
@Siddhant-K-code I and @josead are working on the `Getting Started` guidelines for new contributors. Let us know if you wish to contribute as well.

**Comment by Siddhant-K-code** [comment]
> @Siddhant-K-code I and @josead are working on the `Getting Started` guidelines for new contributors. Let us know if you wish to contribute as well.

Yes, I can work with the `loaders` and building, testing!!
