### ISSUE TITLE
Errors in building metacall with visual studio

### ISSUE THREAD

**Issue by samarthpusalkar** [metacall/core#90]
It showed some errors when I tried to build the visual studio project file made with cmake.
![Capture__](https://user-images.githubusercontent.com/68862617/111319219-c34b4c00-868b-11eb-82cc-51b0399d5237.PNG)

**Comment by Siddhant-K-code** [comment]
The optimization setting Maximize Speed (/O2) is incompatible to the Basic Runtime Checks setting of Code Generation.

To change the settings for Basic Runtime Checks:

Solution -> Properties -> Configuration Properties -> C/C++ -> Code Generation -> Basic Runtime Checks

Set it to "Default", and it should work.

![image](https://user-images.githubusercontent.com/55068936/111325225-7e2a1880-8691-11eb-9c68-9440a704c0ef.png)


> Source : https://stackoverflow.com/questions/37007939/command-line-error-d8016-o2-and-rtc1-command-line-options-are-incompatibl

**Comment by viferga** [comment]
@samarthpusalkar By default metacall is configured as `CMAKE_BUILD_TYPE` as Release. This means you can only build as Release, although Visual Studio lets you to build in Debug or Release no matter what you configured in CMake.

To get rid of this bug select `Release` in the IDE and it will build properly.
