### ISSUE TITLE
Errors in building solution in Visual Studio

### ISSUE THREAD

**Issue by samarthpusalkar** [metacall/core#93]
When building solution in release mode I get the following errors:
![Capture_1](https://user-images.githubusercontent.com/68862617/111337001-b7678600-869b-11eb-96f5-550d742cc895.PNG)

**Comment by viferga** [comment]
Can you try to disable detours and fork safety?
`OPTION_BUILD_DETOURS`=`OFF`
`OPTION_FORK_SAFE`=`OFF`

**Comment by viferga** [comment]
Anyway, I think a windows script for configuring this properly and executing the `msbuild` will be something more interesting, so you can avoid configuring this by hand. All the problems you had were due to configuration.

**Comment by samarthpusalkar** [comment]
Disabling BUILD_DETOURS and FORK_SAFE worked.
