### ISSUE TITLE
Types like function, class, object not mentioned on docs

### ISSUE THREAD

**Issue by siv2r** [metacall/core#97]
## 📚 Documentation

The types `Future`, `Function`, `Class`, `Object` are not mentioned in the documentation of [Type System](https://github.com/metacall/core/tree/develop/docs#521-type-system) under [Reflect](https://github.com/metacall/core/tree/develop/docs#52-reflect). 

These are present in the codebase (under reflect module)
https://github.com/metacall/core/blob/52572bc3de960da922a4032df2f6b4d6be21221a/source/reflect/source/reflect_type_id.c#L40-L45

Is there any specific reason for this? I can add them if needed :)

**Comment by siv2r** [comment]
Sure!! I will do it soon.

**Comment by siv2r** [comment]
What does `Future` mean?

**Comment by viferga** [comment]
> What does `Future` mean?

Future is a Promise in Node Loader, and any other type equivalent in other languages. It is only implemented in NodeJS at the moment.

**Comment by siv2r** [comment]
Closing the issue since #101 fixes this
